#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 02-Mar-2023 09:32:21
#--------------------------------------------------------------
data_source <- "FLUXNET" #Indicate to download data from Database_FLUXNET
site    <- "STJ"
yrs     <- 2017:2021 # Make sure that you process all years the first time (or if you need to go back and re-process data from past years)
db_root <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/Database_FLUXNET"
fx_path <- "/Users/sara/Code/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 2
pthDatabase    <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/Database_FLUXNET"
pthBiometR     <- "/Users/sara/Code/Biomet.net/R/database_functions"
pthLogFile     <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/Database/Calculation_Procedures/TraceAnalysis_ini/STJ/log/STJ_ThirdStageCleaning.log"
ini_path       <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/Database/Calculation_Procedures/TraceAnalysis_ini/STJ"
